---
title: "산업연관표 분석"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

작업순서

1. ECOS류의 2015년 소분류 투입산출표를 통해 대분류 투입산출표 도출

2. 대분류 투입산출표(생산자가격_총거래표)를 바탕으로 총투입계수 및 국산투입계수, 생산유발계수 등 도출

3. 투입계수를 바탕으로 특정 부문의 산업구조를 파악

4. 생산유발계수, 부가가치유발계수의 2010년, 2015년 연도별 비교 그래프(2015년 기준년 산업연관표 작성결과 당행 보도자료 참조)



## 1.기본 세팅

```{r initial settings}
rm(list=ls())
setwd("c:/Users/user/Documents/2019IO")

# 라이브러리 로딩
packages = c('tidyverse', 'XLConnect' )
lapply(packages, require, character.only = T)
```


## 2.대분류 투입산출표(생산자가격_총거래표)를 바탕으로 총투입계수 및 국산투입계수, 생산유발계수 등 도출

```{r calculate}
# 대분류 투입산출표 로딩
raw <- loadWorkbook("c:/Users/user/Documents/2019IO/data/IO_tab_2015_major_cat_f.xlsx")

# 생산자 가격 총거래표 sheet 로딩
data <- readWorksheet(raw, sheet = 1, startRow = 7, startCol = 3, header = F)

# 각 열의 이름 지정
colname_sector <- readWorksheet(raw, sheet = 1, startRow = 6, endRow = 6, startCol = 3, header = F) 
colnames(data) <- colname_sector

# tbl형태로 데이터 변환
data_tbl <- as_tibble(data)


# 중간수요
data_1 <- select(data_tbl, '농림수산품' : '기타')
intermediate_demand <- matrix(unlist(data_1[-c(34:40), ]), nrow = 33, byrow = F)

# 부가가치
added_value <-  unlist(data_1[39, ])

# 총투입=산출액(자가공정산출액 포함)
x <- unlist(data_1[40, ])

# 최종수요
y <- select(data_tbl, "최종수요계")
y <- unlist(y[-c(34 : 40), ])

# 수입
m <- select(data_tbl, "수입")
m <- unlist(m[-c(34 : 40), ])


# 투입계수행렬
x_1 <- matrix(rep(x, times = 33), nrow = 33, byrow = T)
A <- intermediate_demand / x_1
colnames(A) <- colname_sector[1,  1 : 33]

# 부가가치율
added_value_rate <- added_value / x

# 생산유발계수 (1)형
I <- diag(x = 1, nrow = 33)
B <- solve(I - A)

```


## 3.투입계수를 바탕으로 특정 부문의 산업구조를 파악

```{r coeficient}
# 입력값 설정
n <- dim(A)[1] ## 투입계수 행렬의 크기 = 산업의 개수
target <- 17 ## 분석대상 산업, ex) 전력, 가스 및 증기 : 17


# 파급경로 생성(단계별)
T1 <- cbind(rep(target,n),seq(1,n)) # 1단계 파급경로 행렬(n*2)

T2 <- matrix(0,nrow=n^2,ncol=3)
tem <- matrix(0,nrow=n^2,ncol=2)
for (z in 1:n){
  for (i in 1:dim(T1)[1]){
    for(j in 1:dim(T1)[2]){
      tem[n*(z-1)+i,j] <- T1[i,j]
    }}}
T2_new <- rep(seq(1,n), each=n^1)
T2 <- cbind(tem,T2_new) # 2단계 파급경로 행렬(n^2*3)

T3 <- matrix(0,nrow=n^3,ncol=4)
tem <- matrix(0,nrow=n^3,ncol=3)
for (z in 1:n){
  for (i in 1:dim(T2)[1]){
    for(j in 1:dim(T2)[2]){
      tem[n^2*(z-1)+i,j] <- T2[i,j]
    }}}
T3_new <- rep(seq(1,n), each=n^2)
T3 <- cbind(tem,T3_new) # 3단계 파급경로 행렬(n^3*4)

T4 <- matrix(0,nrow=n^4,ncol=5)
tem <- matrix(0,nrow=n^4,ncol=4)
for (z in 1:n){
  for (i in 1:dim(T3)[1]){
    for(j in 1:dim(T3)[2]){
      tem[n^3*(z-1)+i,j] <- T3[i,j]
    }}}
T4_new <- rep(seq(1,n), each=n^3)
T4 <- cbind(tem,T4_new) # 4단계 파급경로 행렬(n^4*5)


# 파급효과 계산(단계별)  * 파급효과: 각 단계별 투입계수의 곱

V1 <- matrix(0,nrow=dim(T1)[1],ncol=1)
for (m in 1:dim(T1)[1]){
  V1[m,1] <- A[T1[m,2],T2[m,1]]
}

V2 <- matrix(0,nrow=dim(T2)[1],ncol=1)
for (m in 1:dim(T2)[1]){
  V2[m,1] <- A[T2[m,2],T2[m,1]]*A[T2[m,3],T2[m,2]]
}

V3 <- matrix(0,nrow=dim(T3)[1],ncol=1)
for (m in 1:dim(T3)[1]){
  V3[m,1] <- A[T3[m,2],T3[m,1]]*A[T3[m,3],T3[m,2]]*A[T3[m,4],T3[m,3]]
}

V4 <- matrix(0,nrow=dim(T4)[1],ncol=1)
for (m in 1:dim(T4)[1]){
  V4[m,1] <- A[T4[m,2],T4[m,1]]*A[T4[m,3],T4[m,2]]*A[T4[m,4],T4[m,3]]*A[T4[m,5],T4[m,4]]
}

# 종합

V <- rbind(V1,V2,V3,V4)
x <- dim(V)

T <- matrix(0,ncol=5,nrow=x)

T[1:dim(V1)[1],1:2] <- T1

r2a<-1+dim(V1)[1]
r2z<-dim(V1)[1]+dim(V2)[1]
T[r2a:r2z,1:3] <- T2

r3a<-1+dim(V1)[1]+dim(V2)[1]
r3z<-dim(V1)[1]+dim(V2)[1]+dim(V3)[1]
T[r3a:r3z,1:4] <- T3

r4a<-1+dim(V1)[1]+dim(V2)[1]+dim(V3)[1]
r4z<-dim(V1)[1]+dim(V2)[1]+dim(V3)[1]+dim(V4)[1]
T[r4a:r4z,1:5] <- T4

final <- cbind(V,T) ## type : double
dtfm <- data.frame(final) ## type : data frame
colnames(dtfm)<-c("obj","s1","s2","s3","s4","s5")

# 결과 내보내기
lookup<-arrange(dtfm,desc(obj))
lookup[1:100,]

```


## 4-1.생산유발계수의 2010년, 2015년 연도별 비교 그래프(2015년 기준년 산업연관표 작성결과 당행 보도자료 참조)
```{r graph}
# 데이터 로딩, 한국은행 홈페이지 2015년 기준년 산업연관표 작성결과 통계요약표의 생산유발계수 sheet를 csv파일로 저장하여 이용 
production_inducement_tab <- read.csv('c:/Users/user/Documents/2019IO/data/production_inducement_tab.csv', header = T, stringsAsFactors = F)

# 데이터 개관
head(production_inducement_tab)

# 데이터 정리
# 'X.','X','X.1' column을 통합하여 sector column을 생성
production_inducement_tab <- production_inducement_tab %>% unite(col = 'sector', X.,X,X.1, sep = "")  

# NA포함 column, 차이 변수 column을 제외하고 sector, 연도 column만을 선택 
production_inducement_tab <- production_inducement_tab %>% select(sector, starts_with('X20'))

# 연도 column의 이름 변경 
production_inducement_tab <- production_inducement_tab %>% rename('2000년' = X2000년.A.,
                                          '2005년' = X2005년.B.,
                                          '2010년' = X2010년.C.,
                                          '2015년' = X2015년.D.)

# 각주 행 삭제
production_inducement_tab <- production_inducement_tab[c(-45 : -48), ]

# sector column 산업 분류명 다듬기
production_inducement_tab$sector <- gsub('[?]', '', production_inducement_tab$sector) 
production_inducement_tab$sector <- gsub('2)', '', production_inducement_tab$sector)
production_inducement_tab$sector <- gsub('3)', '', production_inducement_tab$sector)

# 주요 산업 부분만 추리기
production_inducement_tab_major <- production_inducement_tab[c(2, 3, 11, 16, 17, 18, 21), ]

# 그래프 그리기 
ggplot(data = production_inducement_tab_major) +
  geom_point(mapping = aes(x = production_inducement_tab_major$'2010년', y = production_inducement_tab_major$'2015년', color = sector)) +
  xlab('2010년') + ylab('2015년') + coord_cartesian(xlim = c(1, 2.5), ylim = c(1, 2.5)) +
  geom_abline(intercept = 0, slope = 1, color = 'grey', size = 0.4, linetype = 'dashed')
```

## 4-2.부가가치유발계수의 2010년, 2015년 연도별 비교 그래프(2015년 기준년 산업연관표 작성결과 당행 보도자료 참조)

```{r grpah2}
# 데이터 로딩, 한국은행 홈페이지 2015년 기준년 산업연관표 작성결과 통계요약표의 부가가치계수 sheet를 csv파일로 저장하여 이용 
add_value_tab <- read.csv('c:/Users/user/Documents/2019IO/data/add_value_tab.csv', header = T, stringsAsFactors = F)

# 'X.','X','X.1' column을 통합하여 sector column을 생성
add_value_tab <- add_value_tab %>% unite(col = 'sector', X.,X,X.1, sep = "")  

# NA포함 column, 차이 변수 column을 제외하고 sector, 연도 column만을 선택 
add_value_tab <- add_value_tab %>% select(sector, starts_with('X20'))

# 연도 column의 이름 변경 
add_value_tab <- add_value_tab %>% rename('2000년' = X2000년.A.,
                                          '2005년' = X2005년.B.,
                                          '2010년' = X2010년.C.,
                                          '2015년' = X2015년.D.)

# 각주 행 삭제
add_value_tab <- add_value_tab[c(-45 : -48), ]

# sector column 산업 분류명 다듬기
add_value_tab$sector <- gsub('[?]', '', add_value_tab$sector) # gsub function은 특정 문자열을 찾아 바꾸는 함수
add_value_tab$sector <- gsub('2)', '', add_value_tab$sector)
add_value_tab$sector <- gsub('3)', '', add_value_tab$sector)

# 주요 산업 부분만 추리기
add_value_tab_major <- add_value_tab[c(1, 5, 10, 11, 16, 18, 41), ]

# 그래프 그리기
ggplot(data = add_value_tab_major) +
  geom_point(mapping = aes(x = add_value_tab_major$'2010년', y = add_value_tab_major$'2015년', color = sector)) +
  xlab('2010년') + ylab('2015년') + coord_cartesian(xlim = c(0.4, 1), ylim = c(0.4, 1)) +
  geom_abline(intercept = 0, slope = 1, color = 'grey', size = 0.4, linetype = 'dashed')
```
